### ISSUE TITLE
Choice of flash attention implementation

### ISSUE THREAD

**Issue by mantle2048** [luyug/magix#1]
Hi, thanks a lot for providing such elegant and concise code!

I would like to ask about the choice of flash attention implementation.

In `llama_model.py`, `attn_ops` and `tpu_attn_ops` in `jax.experimental.pallas.ops` are imported, but ultimately you chose the version implemented by `transformer_engine` (`fused_attn`). 

What's the consideration for this choice? Is it because the latter offers better performance?

**Comment by luyug** [comment]
The `tpu_attn_ops` is for TPU so unless you run on it, it should not be relevant. I did not drop that in for now because it does not work on certain generations of TPUs.
As for `attn_ops`, it is ultimately a triton kernel that ends up being less performant than the nvidia implementation (much less performant on Hopper), probably due to less optimal implementation as well as limitations in the triton compiler.

**Comment by mantle2048** [comment]
Cool, got it!
